# Generated by Django 3.2.16 on 2022-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_number', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('contactname', models.CharField(blank=True, db_column='ContactName', max_length=50, null=True)),
                ('contactphone', models.CharField(blank=True, db_column='ContactPhone', max_length=50, null=True)),
                ('getscores', models.IntegerField(blank=True, db_column='GetScores', null=True)),
                ('contactname2', models.CharField(blank=True, db_column='ContactName2', max_length=50, null=True)),
                ('contactphone2', models.CharField(blank=True, db_column='ContactPhone2', max_length=50, null=True)),
                ('contactemail', models.CharField(blank=True, db_column='ContactEmail', max_length=50, null=True)),
                ('website', models.CharField(blank=True, db_column='Website', max_length=50, null=True)),
                ('startdate', models.DateTimeField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.DateTimeField(blank=True, db_column='EndDate', null=True)),
                ('starttime', models.CharField(blank=True, db_column='StartTime', max_length=8, null=True)),
                ('intervals', models.IntegerField(blank=True, db_column='Intervals', null=True)),
                ('gameduration', models.IntegerField(blank=True, db_column='GameDuration', null=True)),
                ('maxpoints', models.IntegerField(db_column='MaxPoints')),
                ('active', models.IntegerField(db_column='Active')),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=2, null=True)),
                ('bracketstyle', models.IntegerField(blank=True, db_column='BracketStyle', null=True)),
                ('smsid', models.IntegerField(blank=True, db_column='SMSID', null=True)),
                ('blocksms', models.IntegerField(blank=True, db_column='BlockSMS', null=True)),
                ('robot', models.IntegerField(blank=True, db_column='ROBOT', null=True)),
                ('divisiondesc', models.CharField(blank=True, db_column='DivisionDesc', max_length=10, null=True)),
                ('genderdesc', models.CharField(blank=True, db_column='GenderDesc', max_length=10, null=True)),
                ('multiregistrations', models.IntegerField(blank=True, db_column='MultiRegistrations', null=True)),
                ('lastrelease', models.DateTimeField(blank=True, db_column='LastRelease', null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
                ('updateuser', models.CharField(blank=True, db_column='UpdateUser', max_length=50, null=True)),
                ('registrationpriceperteam', models.DecimalField(db_column='RegistrationPricePerTeam', decimal_places=2, max_digits=6)),
                ('registrationfee', models.DecimalField(db_column='RegistrationFee', decimal_places=2, max_digits=6)),
                ('registrationstartdate', models.DateTimeField(db_column='RegistrationStartDate')),
                ('registrationenddate', models.DateTimeField(db_column='RegistrationEndDate')),
                ('registrationcountteams', models.IntegerField(db_column='RegistrationCountTeams')),
                ('registrationdiscount', models.DecimalField(blank=True, db_column='RegistrationDiscount', decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'tbl_Tournaments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentInformation',
            fields=[
                ('letterid', models.AutoField(db_column='LetterID', primary_key=True, serialize=False)),
                ('letter', models.TextField(blank=True, db_column='Letter', null=True)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=50, null=True)),
                ('flyerurl', models.CharField(blank=True, db_column='FlyerURL', max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_InfoLetter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.BinaryField(blank=True, db_column='Logo', null=True)),
            ],
            options={
                'db_table': 'tbl_Logos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastupdate', models.DateTimeField(blank=True, db_column='LastUpdate', null=True)),
                ('isowner', models.BooleanField(db_column='IsOwner')),
            ],
            options={
                'db_table': 'tbl_TournamentUsers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentUserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tophone', models.CharField(db_column='ToPhone', max_length=50)),
                ('activationcode', models.CharField(blank=True, db_column='ActivationCode', max_length=6, null=True)),
                ('createdt', models.DateTimeField(db_column='CreateDT')),
                ('updatedt', models.DateTimeField(db_column='UpdateDT')),
            ],
            options={
                'db_table': 'tbl_TournamentUserInvitations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(db_column='Access', max_length=50)),
                ('accesscode', models.IntegerField(db_column='AccessCode')),
                ('updatedate', models.DateTimeField(db_column='UpdateDate')),
                ('updateuser', models.CharField(db_column='UpdateUser', max_length=20)),
            ],
            options={
                'db_table': 'tbl_TournamentUserRoles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tbl_UsersFavouritesTournaments',
                'managed': False,
            },
        ),
    ]
