# Generated by Django 3.2.16 on 2022-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScorbotEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(blank=True, db_column='Descr', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_EventType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScorbotGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradenbr', models.CharField(blank=True, db_column='GradeNbr', max_length=2, null=True)),
                ('grade', models.CharField(blank=True, db_column='Grade', max_length=50, null=True)),
                ('byage', models.CharField(blank=True, db_column='ByAge', max_length=10, null=True)),
                ('bygrade', models.CharField(blank=True, db_column='ByGrade', max_length=10, null=True)),
            ],
            options={
                'db_table': 'tbl_Grades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScorbotModule',
            fields=[
                ('moduleid', models.IntegerField(db_column='ModuleID', primary_key=True, serialize=False)),
                ('module', models.CharField(blank=True, db_column='Module', max_length=50, null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
                ('updateuser', models.CharField(blank=True, db_column='UpdateUser', max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_Modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScorbotStatus',
            fields=[
                ('statusid', models.AutoField(db_column='StatusID', primary_key=True, serialize=False)),
                ('statusdesc', models.CharField(blank=True, db_column='StatusDesc', max_length=50, null=True)),
                ('details', models.CharField(blank=True, db_column='Details', max_length=255, null=True)),
                ('ranking', models.IntegerField(blank=True, db_column='Ranking', null=True)),
            ],
            options={
                'db_table': 'tbl_Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScorbotTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=50, null=True)),
                ('minutes', models.IntegerField(blank=True, db_column='Minutes', null=True)),
            ],
            options={
                'db_table': 'tbl_Time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScorbotTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_column='Code', max_length=5, null=True)),
                ('descrip', models.CharField(blank=True, db_column='Descrip', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_Zones',
                'managed': False,
            },
        ),
    ]
