# Generated by Django 3.2.16 on 2022-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.AutoField(db_column='TeamID', primary_key=True, serialize=False)),
                ('smsid', models.IntegerField(blank=True, db_column='SMSID', null=True)),
                ('teamtxtid', models.IntegerField(blank=True, db_column='TeamTxtID', null=True)),
                ('gradeid', models.IntegerField(blank=True, db_column='GradeID', null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=10, null=True)),
                ('teamname', models.CharField(blank=True, db_column='TeamName', max_length=50, null=True)),
                ('coachname', models.CharField(blank=True, db_column='CoachName', max_length=50, null=True)),
                ('coachphone', models.CharField(blank=True, db_column='CoachPhone', max_length=50, null=True)),
                ('coachemail', models.CharField(blank=True, db_column='CoachEmail', max_length=50, null=True)),
                ('assistantname', models.CharField(blank=True, db_column='AssistantName', max_length=50, null=True)),
                ('assistantphone', models.CharField(blank=True, db_column='AssistantPhone', max_length=50, null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
                ('updateuser', models.CharField(blank=True, db_column='UpdateUser', max_length=50, null=True)),
                ('updatetid', models.IntegerField(blank=True, db_column='UpdateTID', null=True)),
            ],
            options={
                'db_table': 'tbl_Teams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], db_column='Gender', max_length=10, null=True)),
                ('teamname', models.CharField(db_column='TeamName', max_length=50)),
                ('coachname', models.CharField(blank=True, db_column='CoachName', max_length=50, null=True)),
                ('coachphone', models.CharField(blank=True, db_column='CoachPhone', max_length=50, null=True)),
                ('coachemail', models.CharField(blank=True, db_column='CoachEmail', max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('createdt', models.DateTimeField(db_column='CreateDT')),
                ('updatedt', models.DateTimeField(db_column='UpdateDT')),
                ('ranktype', models.IntegerField(blank=True, db_column='RankType', null=True)),
                ('mergedwith', models.IntegerField(blank=True, db_column='MergedWith', null=True)),
                ('yboa_id', models.IntegerField(blank=True, db_column='YBOA_ID', null=True)),
            ],
            options={
                'db_table': 'tbl_TeamsCoach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamFans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournamentid', models.IntegerField(db_column='TournamentID')),
                ('smsid', models.IntegerField(blank=True, db_column='SMSID', null=True)),
                ('teamtxtid', models.IntegerField(blank=True, db_column='TeamTxtID', null=True)),
                ('teamid', models.IntegerField(db_column='TeamID')),
                ('teaminfoid', models.IntegerField(blank=True, db_column='TeamInfoID', null=True)),
                ('teamname', models.CharField(blank=True, db_column='TeamName', max_length=50, null=True)),
                ('cellphone', models.CharField(db_column='CellPhone', max_length=11)),
                ('updatedate', models.DateTimeField(db_column='UpdateDate')),
            ],
            options={
                'db_table': 'tbl_TeamFans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournamentid', models.IntegerField(db_column='TournamentID')),
                ('divisionid', models.IntegerField(db_column='DivisionID')),
                ('poolid', models.IntegerField(blank=True, db_column='PoolID', null=True)),
                ('teamid', models.IntegerField(blank=True, db_column='TeamID', null=True)),
                ('finals', models.IntegerField(db_column='Finals')),
                ('teamnbr', models.IntegerField(blank=True, db_column='TeamNbr', null=True)),
                ('getscores', models.IntegerField(blank=True, db_column='GetScores', null=True)),
                ('teamname', models.CharField(blank=True, db_column='TeamName', max_length=50, null=True)),
                ('coachname', models.CharField(blank=True, db_column='CoachName', max_length=50, null=True)),
                ('coachphone', models.CharField(blank=True, db_column='CoachPhone', max_length=50, null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
                ('updateuser', models.CharField(blank=True, db_column='UpdateUser', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_TeamInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamInfoNew',
            fields=[
                ('teaminfoid', models.AutoField(db_column='TeamInfoID', primary_key=True, serialize=False)),
                ('teamid', models.IntegerField(blank=True, db_column='TeamID', null=True)),
                ('finals', models.IntegerField(db_column='Finals')),
                ('ranking', models.IntegerField(blank=True, db_column='Ranking', null=True)),
                ('teamtxtid', models.IntegerField(blank=True, db_column='TeamTxtID', null=True)),
                ('teamname', models.CharField(blank=True, db_column='TeamName', max_length=50, null=True)),
                ('coachname', models.CharField(blank=True, db_column='CoachName', max_length=50, null=True)),
                ('coachphone', models.CharField(blank=True, db_column='CoachPhone', max_length=50, null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
                ('updateuser', models.CharField(blank=True, db_column='UpdateUser', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_TeamInfo_New',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamid', models.IntegerField(blank=True, db_column='TeamID', null=True)),
                ('tournamentid', models.IntegerField(blank=True, db_column='TournamentID', null=True)),
                ('gameid', models.IntegerField(blank=True, db_column='GameID', null=True)),
                ('pointsearned', models.IntegerField(blank=True, db_column='PointsEarned', null=True)),
                ('games', models.IntegerField(blank=True, db_column='Games', null=True)),
                ('wins', models.IntegerField(blank=True, db_column='Wins', null=True)),
                ('isadded', models.BooleanField(db_column='IsAdded')),
            ],
            options={
                'db_table': 'tbl_TeamPoints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamsCoachTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamtxtid', models.IntegerField(db_column='TeamTxtID')),
                ('createdt', models.DateTimeField(db_column='CreateDT')),
            ],
            options={
                'db_table': 'tbl_TeamsCoachTournaments',
                'managed': False,
            },
        ),
    ]
