# Generated by Django 3.2.16 on 2022-11-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playingup', models.IntegerField(blank=True, db_column='PlayingUp', null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
                ('updateuser', models.CharField(blank=True, db_column='UpdateUser', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_Registrations',
                'managed': False,
            },
        ),
    ]
