# Generated by Django 3.2.16 on 2022-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='Zipcode', max_length=50, null=True)),
                ('director', models.CharField(blank=True, db_column='Director', max_length=50, null=True)),
                ('cellphone', models.CharField(blank=True, db_column='CellPhone', max_length=50, null=True)),
                ('director2', models.CharField(blank=True, db_column='Director2', max_length=50, null=True)),
                ('cellphone2', models.CharField(db_column='CellPhone2', max_length=48)),
                ('director3', models.CharField(blank=True, db_column='Director3', max_length=50, null=True)),
                ('cellphone3', models.CharField(db_column='CellPhone3', max_length=48)),
                ('active', models.IntegerField(blank=True, db_column='Active', null=True)),
                ('getscores', models.IntegerField(blank=True, db_column='GetScores', null=True)),
                ('position', models.IntegerField(db_column='Position')),
            ],
            options={
                'db_table': 'tbl_Locations',
                'managed': False,
            },
        ),
    ]
