# Generated by Django 3.2.16 on 2022-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScorbotOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('shortname', models.CharField(db_column='ShortName', max_length=15)),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('contactname', models.CharField(blank=True, db_column='ContactName', max_length=50, null=True)),
                ('contactphone', models.CharField(blank=True, db_column='ContactPhone', max_length=50, null=True)),
                ('contactemail', models.CharField(blank=True, db_column='ContactEmail', max_length=50, null=True)),
                ('director', models.IntegerField(blank=True, db_column='Director', null=True)),
                ('createdt', models.DateTimeField(blank=True, db_column='CreateDT', null=True)),
                ('updatedt', models.DateTimeField(blank=True, db_column='UpdateDT', null=True)),
                ('tiebreakingurl', models.TextField(blank=True, db_column='TieBreakingURL', null=True)),
            ],
            options={
                'db_table': 'tbl_Organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScorbotSMSPhone',
            fields=[
                ('smsid', models.AutoField(db_column='SMSID', primary_key=True, serialize=False)),
                ('smsphoneid', models.IntegerField(blank=True, db_column='SMSPhoneID', null=True)),
                ('smsphone', models.CharField(blank=True, db_column='SMSPhone', max_length=50, null=True)),
                ('descrip', models.CharField(blank=True, db_column='Descrip', max_length=200, null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=100, null=True)),
                ('effectiveyear', models.IntegerField(blank=True, db_column='EffectiveYear', null=True)),
                ('active', models.BooleanField(blank=True, db_column='Active', null=True)),
            ],
            options={
                'db_table': 'tbl_SMSPhones',
                'managed': False,
            },
        ),
    ]
