name: Deploy to EC2

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ./deployment/playbooks
          playbook: staging.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          options: |
              --inventory ../inventory/hosts
              --user ubuntu
